oletools/olevba.py
oletools/ppt_parser.py

So far, the --deobf option got lost if --json was enabled because the options.deobfuscate was not forwarded to analyze_macros(). Corrected this
Also: added a warning (but only at log.info level) if params are changed/ignored; ensured that the 'code' field in json result is always there

Fix deof with json

---

oletools/olevba.py

We have an example xlsx file where ole.openstream() fails in _extract_vba for 3 out of 10 modules; I therefore wrapped the iteration in a try-except to still parse the rest of the file. MS office and LibreOffice open the file without any problem/warning
Also a commit with small changes to json2ascii (its output was not worth of info-level logging)

Robustify extact vba

---

oletools/olevba.py

I found the reason for the openstream problem: the stream names may be unicode (e.g. Лист2 or  ЭтаКнига), and _extract_vba always tried the non-unicode module name (decoded with cp1252 but that does not, for example, contain cyrillic letters). To stay compatible with the earlier code, _extract_vba now tries different module/stream names now
Also warn properly (at warning level) if all atempts to load module fail

Unicode vba stream names

---

oletools/olevba.py
oletools/ppt_parser.py

As hinted at earlier: we added a --relaxed option to olevba.
After adding my first robustify-olevba-patch (simple try-except around openstream), we realized that there are a few more cases where subfiles or substreams/modules are not parsed in case there is an error and only info- or debug-logging would reveal that there is potentially unparsed code.
To fix this, we made the parsing much stricter (e.g. raise SubstreamOpenError if cannot open module) by default. The old behaviour (accept everything silently just like MS office does) can be obtained by adding --relaxed. A few warnings are only log.info or log.debug now if --relaxed is set (per default, they raise exceptions now)
This branch is based on the yet unmerged unicode-vba-stream-names; so the first 2 commits here are the same as in …

Relaxed checking opt

---

oletools/oleobj.py
oletools/rtfobj.py

I pass the rtfobj full python3.5 but the compliant with python 2.7 is broken. 
The another thing there is a regression in code: 
```
slarinier@Chise:~/Documents/sources/python/oletools (master)$ python oletools/rtfobj.py ~/Documents/projet/sekoia/Cert/Invest/72b14306c9f95536d03d88cf63204f70630dd9cd00664ad7f86c1d774c8508e9.rtf 
rtfobj 0.48 - http://decalage.info/python/oletools
THIS IS WORK IN PROGRESS - Check updates regularly!
Please report any issue at https://github.com/decalage2/oletools/issues
found object size 70 at index 00004C7F - end 00004D21
saving object to file /home/slarinier/Documents/projet/sekoia/Cert/Invest/72b14306c9f95536d03d88cf63204f70630dd9cd00664ad7f86c1d774c8508e9.rtf_object_00004C7F.raw
extract file embedded in OLE object:
format_id  = 2
class name = …
```

python3.5 compliant only

---

setup.py

Update of  `setup.py` to provide a command line script:
``` 
$ olevba
$ which olevba
/usr/local/bin/olevba 
```
It's not effective for all scripts as it require a main function entrypoint ```main()``` in the script.

Command Line Scripts

---

oletools/mraptor.py
oletools/oledir.py
oletools/olemap.py
oletools/oletimes.py
oletools/olevba.py
oletools/ppt_parser.py
oletools/thirdparty/olefile/olefile.py
oletools/thirdparty/olefile/olefile2.py
oletools/thirdparty/tablestream/tablestream.py

I don't change the regex logical. The code decode VBA macros with bytes and as soon as possible it decode in urtf-8 to match with regex. I modify also the export json because unicode doesn't exist in python 3.5. It's replaced by str and it's not the function to decode. I add the if the json_obj is bytes like hexstring.

Olevba compliant python3.5

---

oletools/olevba.py
oletools/olevba3.py

Add two commonly used memory manipulation Windows API functions to the suspicious keywords list. This has been observed with Vawtrak/Hancitor malicious Word docs.

Add VirtualAllocEx and RtlMoveMemory to SUSPICIOUS_KEYWORDS

---

oletools/olevba.py

The fix in #107 was incomplete, since it corrected the expected variable passed to the UnexpectedDataError.__init__ function, it did not address the fact that UnexpectedDataError 'expected' argument be a integer.  When raising the UnexpectedDataError exception when parsing the REFERENCENAME data, 'expected' is passed as a tuple of integers.  This causes a ValueError during the string formatting option, since it uses the X format option.
This allows olevba to gracefully fail on malformed documents, instead of raising a unhandled exception to the caller.

Update __init__ of UnexpectedDataError exception

---

setup.py

The zipfile27 package isn't installed by setup.py producing the following traceback when olevba is run:
```
Traceback (most recent call last):
File "/usr/bin/olevba", line 9, in <module>
load_entry_point('oletools==0.51a1', 'console_scripts', 'olevba')()
File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
return ep.load()
File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2355, in load
return self.resolve()
File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2361, in resolve
module = __import__(self.module_name, fromlist=['__name__'], level=0)
File …
```

Added zipfile27 package to setup.py

---

oletools/thirdparty/olefile/olefile.py

A large num_props value will cause memory bloat (via the range usage) and potentially billions of useless logs in relaxed mode.  Clamp it to a value that has a reasonable chance of working without generating exceptions.

Clamp num_props to prevent excessive resource usage

---

.travis.yml
README.md
setup.py
tests/rtfobj/test_issue_185.py
tests/test-data/rtfobj/issue_185.rtf
tests/testdata_reader.py

I've added an initial support for unit tests and my sample test case was for #185.
The initial idea is to add test cases as the bugs are fixed to prevent regressions, but this can be further extended to some test first-like approach for new implementations.
Currently the tests run on Python 2.x only, so we still need to add support for v3.
I have also added Travis CI integration and its status badge to the README page. Currently the badge points at my fork, but if this is accepted I can change it before it gets merged (and @decalage2 also needs to authorize Travis on this repo).

Initial support for unit tests

---

oletools/msodde.py

DDE / DDEAUTO can also be specified with  
```
<w:fldSimple w:instr='DDE "C:\\WINDOWS\\system32\\cmd.exe" "/k powershell.exe"' w:dirty="true">
<w:r>
<w:t>Pew</w:t>
</w:r>
</w:fldSimple>
```
This adds some additional parsing to extract the link if it is inside a ```w:fldSimple``` element

Adds an additional check to detect DDE

---

oletools/msodde.py

Lots of minor fixes and improvements to msodde.py:
(did not touch other user's code parts except where necessary)
- replace #print(..) with either log.debug(..) or remove it
- warn if combining --json with -ldebug
- delay combining dde-links to single text just like process_xml
- fix print(..) of unicode in dde-links of re-directing output or piping it to other command
- fix some complaints from pylint: base except, whitespace, missing docs
- remove empty dde-links from result output
- copy hack from olevba.py to run without installing
Some of this is required for adding more unittests (see next pull request)

Minor msodde fixes

---

.travis.yml
oletools/olevba3.py

I've changed the Travis configuration to also run tests on Python 3 and newer versions.
olevba3 required a little extra check so [one test from test_output.py](https://github.com/decalage2/oletools/blob/1b7f44d128dcb623ec27e3d042d4e3ba858470dd/tests/json/test_output.py#L83) could pass.

Run tests on python3

---

setup.py

setup.py didn't include olevba3 as a command line tool.

added olevba3 to exposed command line tools

---

oletools/olevba3.py

This fixes #238 by converting the bytes in decompress_stream to a byte_array in olevba3, which grows more efficiently since it's mutable vs the immutable bytes.
Testing on 32d37985044df7609714b0b3eff2230d shows a 100x performance increase.

convert byte concat to bytearray

---

oletools/olevba.py
oletools/olevba3.py
oletools/rtfobj.py
tests/json/test_output.py
tests/rtfobj/test_is_rtf.py

olevba[3] often takes ages to scan RTF because it handles them like TXT and finds lots of bogus "hex strings" that are actually only regular rtf commands.
This is a waste of time since RTF itself cannot contain VBA/Macro code. The only way to carry bad stuff for RTF is to have it embedded as an own file, for which rtfdump is the right utility.
Therefore, we suggest skipping RTF files in olevba[3] with a message saying that rtfobj should be run instead.
Created a general-purpose check function is_rtf in rtfobj, based also on http://www.decalage.info/rtf_tricks

Olevba skip rtf

---

oletools/rtfobj.py
tests/json/test_output.py
tests/rtfobj/test_is_rtf.py

Following the discussion on #254, this PR removes checks for
uppercased RTF magic since neither Word nor Wordpad accept
those.
Some changes related to PEP8 style were also made.

rtfobj: remove check for uppercased RTF magic

---

oletools/olevba3.py

When using VBA_Parser from olevba3.py, ppt_parser logging is always enabled. This is similar to issue #154, although enable_logging() method is already implemented and ppt_parser logging is handled there, so just remove enable_logging from VBA_Parser.open_ppt().

Fix always enabled logging in PptParser.

---

oletools/oleid.py

Here's how to reproduce the issue (using python 3):
```
$ oleid e39d70df22c45338475656067ad245993db6921bb29aa7156969f4e53fccb222
oleid 0.51 - http://decalage.info/oletools
THIS IS WORK IN PROGRESS - Check updates regularly!
Please report any issue at https://github.com/decalage2/oletools/issues
Filename: e39d70df22c45338475656067ad245993db6921bb29aa7156969f4e53fccb222
Traceback (most recent call last):
File "/usr/local/bin/oleid", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python3.6/site-packages/oletools/oleid.py", line 306, in main
indicators = oleid.check()
File "/usr/local/lib/python3.6/site-packages/oletools/oleid.py", line 188, in check
self.check_flash()
File "/usr/local/lib/python3.6/site-packages/oletools/oleid.py", line 277, in check_flash
found = …
```

Improve detect_flash Python 3 compatibility

---

oletools/ppt_parser.py

Ppt-parser-specific logger is mostly used. Using logger of the main application
prevents from disabling ppt_parser log messages, ppt_parser-specific logger can
be controlled via enable_logging().

Use only module-specific logger in the ppt_parser module.

---

oletools/olevba3.py

extract_macros() returns vba_code as bytes or string (string only for
OpenXML/PPT -- open_text() decodes bytes to string).
This way it is already implemented in process_file() and process_file_json().
Sample hash: 586DB43601FB55E89E67DFE569E1E9983779722ED47A8E1F23ADF54D04D3DF4B

Fix AttributeError: 'str' object has no attribute 'decode'.

---

oletools/msodde.py

msodde would sometimes complain that something should be an error condition.
Determined that most of these are not and raise proper error for those that
really are an error.

msodde: Determine when error condition actually is one

---

oletools/common/clsid.py

CVE-2018-8174: https://securelist.com/root-cause-analysis-of-cve-2018-8174/85486/
Uses the same technique as CVE-2017-0199 in the RTF document.
URL Moniker ---> Media Negotiation(server returns content-type: text/html, CVE-2017-0199 server returns content-type: application/hta, which was already blocked by "IActivationFilter" in MSO.DLL) ---> HTML triggers a vulnerability in vbscript.dll(CVE-2018-8174)

Update clsid.py (CVE-2018-8174)

---

oletools/msodde.py
tests/msodde/test_csv.py

Extend formula to find DDE-Links in CSV as described in issue #259 . Added simple unittest.
The resulting output will not be as perfectly cleaned as before (may contain the "SUM(" or the wrapping ""), but all samples mentioned in issue are matched by regex.

Csv formula extension

---

oletools/rtfobj.py

The condition is always False because `self.data[self.index]` returns integer.
Try to put this in code before the condition:
```
>>> print(type(self.data[self.index]))  # <class 'int'>
>>> print(self.data[self.index])        # 32
```
Thus even with space at self.index it fails:
`>>> 32 == ' '  # False`

Fix ignoring of optional whitespace after \bin.

---

oletools/olevba3.py

unichr has been replaced by chr in python 3

Fix NameError: unichr not defined in python3

---

.travis.yml
oletools/ooxml.py
tests/msodde/test_csv.py

* Updated .travis.yml to use more recent versions of python 3.7 and 3.8(nightly) (Travis' `python: nightly` was an outdated 3.7)
* Removed usage of `raise StopIteration` which is deprecated from 3.7 on (PEP-479)
* `csv.Sniffer` was changed [lately](https://bugs.python.org/issue30157) and behaves now different in some cases (this also affects python 2.7 and 3.6). This PR changes the generated test CSV to also contain a delimiter at the end of the line of `sample_core`. 
I'm not 100% sure if this is the correct way to fix this now failing test. Since now when using a new version of python and if there is no delimiter in this line `csv.Sniffer` might detect the quoting-character of this line as delimiter character and therefore not extract the correct cells/values.

Stop tests from failing when using python3.7 

---

oletools/rtfobj.py

A missing "b" was the reason for the different output in python2 and python3 in #347.
With this PR rtfobj detects the OLE object in python3, too.
rtfobj 0.53.1 on Python 3.6.5 - http://decalage.info/python/oletools
THIS IS WORK IN PROGRESS - Check updates regularly!
Please report any issue at https://github.com/decalage2/oletools/issues
===============================================================================
File: '5771308(1).doc' - size: 92648 bytes
---+----------+---------------------------------------------------------------
id |index     |OLE Object
---+----------+---------------------------------------------------------------
0  |00009BFFh |format_id: 2 (Embedded)
|          |class name: b'B56SHdydZaYzS8GGe'
|          |data size: 3584
|          |CLSID: …

Fix comparsion against string

---

MANIFEST.in

When creating source tarball	via "python setup.py sdist" or
"python setup.py bdist_rpm", then include test code and data so can
still run unittests. This does not affect the rpms.
Tried first to achieve this effect (test[-data] included in source but not
in rpm) using options in setup.py but failed.

setup: create MANIFEST so source-tarball includes tests

---

oletools/rtfobj.py

Small change which uses the extension of an embedded object from the temp_path instead of the filename. 
In cases where the embedded object is an executable file, rtfobj will display a warning for the analyst in red. If the filename extension is altered or removed, the output formatting defaults to yellow.  The extension within the temp path can't be modified otherwise it won't be executed using the correct handler for the filetype. 
In most cases I don't think it matters as an analyst reviewing the output will review all of the artifacts, but it could be used as a method to obfuscate an embedded executable object. Example: Including many embedded objects and other artifacts that fill an analysts screen.

Update rtfobj to use the extension from the temp path of an embedded Package object

---

oletools/oleid.py

Tested on Python 2 (2.7.15) and Python 3 (3.7.2)

Fixing PrettyTable import for oleid (fixes #391)

---

oletools/common/log_helper/_json_formatter.py
oletools/common/log_helper/_logger_adapter.py
oletools/msodde.py
tests/common/log_helper/log_helper_test_imported.py
tests/common/log_helper/log_helper_test_main.py
tests/common/log_helper/test_log_helper.py

Add an optional "type" field to logging calls that is ignored in "regular" logging to console but shows in json output. 
This is a way to bring some kind of structure into json output which since merging of PR #308 (Unified logging with json) is just a list of log-messages wrapped into json. There is no structure any more which of those messages is status, which is result, etc, and that makes parsing json equally complicated as parsing the regular non-json output.
This PR represents a low-impact start of a solution. The "type" field can mark a message as "result", as an example used this in msodde.
This might not be the final word on this topic since the discussion on how to get stable json output is not finished. But it allows to create json output that is much easier to parse until a …

Type-Field in logging

---

oletools/crypto.py
oletools/msodde.py
oletools/oleobj.py
oletools/ppt_record_parser.py
oletools/xls_parser.py
tests/msodde/test_basic.py
tests/msodde/test_crypto.py
tests/oleobj/test_basic.py
tests/oleobj/test_external_links.py
tests/ooxml/test_zip_sub_file.py
tests/test_utils/utils.py

Unittests have been issuing warnings for a while now, "just" wanted to fix these. Turns out, some were right, quite a few file handles did need closing, some tests needed adjustments. Also reduced the output that unittests produced, some problems were hidden in the long stream of irrelevant text output.

Unittest fixes, reduce output

---

oletools/common/log_helper/_json_formatter.py
oletools/crypto.py
oletools/olevba.py
tests/msodde/test_basic.py

This fixes a stupid little bug introduced when integrating crypto into msodde: check whether decryption actually worked and raise appropriate error if not.
Fixed this also in crypto recommendations and created a unittest

Msodde failed decrypt fix

---

oletools/olevba.py

`encoding` parameter is passed to `bytes2str()` and it's also mentioned in its
description but method actually always used UTF-8.

Use given encoding in bytes2str (olevba).

---

oletools/ooxml.py

changed reading mode in ooxml.XMLParser.iter_files() for single xml  to rb. With the 'r' mode, it's impossible to parse excel-xml 2003 and 2007

changed reading mode in ooxml

---

oletools/olevba.py

Reference: https://twitter.com/joe4security/status/1221765460502421504
This method has been widely used by actors related to #Ostap and #Trickbot malware, starting from Jan 2020.
Another example:
https://app.any.run/tasks/8436f1cb-e3c5-4d12-ae3b-508222949121/

added new Autorun method OnConnecting

---

oletools/thirdparty/oledump/plugin_biff.py

The current version has severe performance issues when analyzing some binary xls files. Updating to the latest plugin version solves the problem.

Update plugin to latest version

---

oletools/thirdparty/oledump/plugin_biff.py

Currently plugin_biff.py places 'FLOAT' in the XLM output as the value of float literals. The change in this pull request decodes and places the actual value of the float literal in the XLM output.

Unpack the values of ptgNum float literals.

---

oletools/olevba.py

Fix issue #602 
(Sorry for previous pull request, I committed with the wrong email, tried to fix it and ended up messing up the whole repository. This PR should be alright.)

olevba: prevent side effects on python lib "email"

---

oletools/ppt_parser.py

Another py2/py3-error: returned data is str in py2, bytes in py3
Probably fixes issue #177

ppt_parser: fix type of decompressed data

---

oletools/olevba.py

during object initialization relaxed was set to False all the time, regardless of the command line option.

fixed command line option --relaxed

---

oletools/olevba.py
oletools/ppt_parser.py

This PR adds an option to disable pcode-extraction and renames the existing "pcode" option.
During coding I found a few minor errors that I fixed right away, these are the commits in the beginning. The ppt_parser-commit was cherry-picked from another PR (#450), I needed it for testing. Feel free to just pick&merge part of these.
Rationale behind the main change:
contrary to its help string, option "pcode" does not (any more) determine whether pcode is extracted and analyzed or not. That happens always. It only determines whether the pcode is shown to the user in the normal "detailed" output mode. I also implemented pcode-output in "json" output-mode and added a warning if pcode should be shown in triage mode. I renamed it "show_pcode".
To bring back the original meaning of the …

Pcode options + fixes

---

oletools/oleobj.py

Hello @decalage2,
Thank you for this great tool.
I recently came across this sample which has a relationship, with 'frame' as external link (sha256: 6a5d70c47d314c310003fcd0d74295d2442a27a5de87aedef715e426aa7222bd)
Expected extraction: http://filecopying[.]xyz/KB234520/update/2107SP
However, due to missing commas in the BLACKLISTED_RELATIONSHIP_TYPES, this link is missed. Someone already reported this issue #641 
Please accept the PR, and let me know if you have any comments. Thank you!

oleobj: Missing commas in BLACKLISTED_RELATIONSHIP_TYPES

---

oletools/common/clsid.py
oletools/oledir.py
oletools/rtfobj.py
tests/common/test_clsid.py

This change set ensures that lookups for known class identifiers are always performed with uppercase strings.
An additional unit test ensures that all identifiers are in uppercase only.

ensure uppercase KNOWN_CLSIDS matching

---

oletools/oleid.py

Fix an issue in OleID check_excel()

---

oletools/oleid.py

It's necessary to set self.data if data is not None.
Fixes: #695
Signed-off-by: Jürgen Löhel <juergen.loehel@inlyse.com>

Fixes OleID constructor

---

oletools/olevba.py

When I parse xlm macro from external software using olevba, I found a bug in the following line.
https://github.com/decalage2/oletools/blob/412ee36ae45e70f42123e835871bac956d958461/oletools/olevba.py#L3424-L3430
In order to make it available from external software, I changed the call to be the same as line 3409: 
https://github.com/decalage2/oletools/blob/412ee36ae45e70f42123e835871bac956d958461/oletools/olevba.py#L3409

olevba: fix sys.argv[1] using xlmdeobfuscator

---

oletools/oleobj.py
tests/ftguess/test_basic.py
tests/oleobj/test_basic.py

Encountered malware samples where "Filename" of an embedded file was " " (just a space), but "Source Path" and "Temp Path" contained a proper filename. Seems to be enough for windows to recognize the file type. So extract file name (in particular: the file extension) from paths if "Filename" is not helpful.
Realized that lots of things can go wrong creating filenames: collisions with other files, extremely long names, different path separators ("/" vs "\"). Address these issues, too.

Oleobj preserve file extension

---

tests/msodde/test_basic.py
tests/test_utils/__init__.py
tests/test_utils/testdata_reader.py

Some samples triggered antivirus engines, issues #215 and #217 ended with the agreement to encapsulate problematic samples in encrypted zip containers and decrypt them on-the-fly. Initial support for this was added but that did not cover 5 tests. Create on-the-fly decryption for these tests as well and re-enable them.

tests: Re-enable samples skipped because of #215

---

oletools/olevba.py
tests/olevba/test_basic.py

Fix unittests and problem for olevba in python 2.7

Fix unittests

---

oletools/oleobj.py

Python 3.8+ now produces a SyntaxWarning when identify checks are used with certain literals. This was documented in the 3.8 release notes here https://docs.python.org/3/whatsnew/3.8.html#porting-to-python-3-8
On import, the oletools package currently produces a such a warning message:
```
/usr/local/lib/python3.8/dist-packages/oletools/oleobj.py:581: SyntaxWarning: "is" with a literal. Did you mean "=="?
if idx is -1:
```
This PR changes the identify check to a equality check.

Fix a SyntaxWarning in Python 3.8+

---

requirements.txt
setup.py

All oletools unit tests pass with pyparsing 3.0.9 installed.
This makes it easier to use oletools as a library.

Relax pyparsing requirement. 

---

oletools/oleobj.py

In python 3.12+ this escaping is reported as syntax error. Moving the dash to the end of the regex avoids the need for escaping it.
oletools/oleobj.py:537
/rpmbuild/BUILD/oletools-78b2d459a33df378a4f69ffc6c33313509cecfe4/oletools/oleobj.py:537: SyntaxWarning: invalid escape sequence '\-'
sane_fname = re.sub(u'[^a-zA-Z0-9.\-_ ]', replacement, basepath)

oleobj.py syntax error

---

oletools/rtfobj.py

In python 3.12+ it is reporting the syntax error 
oletools/rtfobj.py:272
/rpmbuild/BUILD/oletools-78b2d459a33df378a4f69ffc6c33313509cecfe4/oletools/rtfobj.py:272: SyntaxWarning: invalid escape sequence '\d'
DECIMAL_GROUP = b'(\d{1,250})'

rtfobj.py syntax error

---

oletools/thirdparty/xxxswf/xxxswf.py

The imp module is removed in 3.12 and causes an error when loading `xxxswf`. The recommended replacement is `importlib` but here the use of imp is actually redundant. When `yara` isn't found the `import yara` statement already throws an `ImportError` for 3.5 and earlier, and for 3.6 and later it throws a `ModuleNotFoundError` which is a subclass of `ImportError` and is caught by the same try catch.

Remove imp import from xxxswf for python 3.12 compatability

---

LICENSE.md
README.md
oletools/README.html
oletools/README.rst
oletools/doc/Contribute.html
oletools/doc/Home.html
oletools/doc/Install.html
oletools/doc/License.html
oletools/doc/License.md
oletools/doc/mraptor.html
oletools/doc/olebrowse.html
oletools/doc/oledir.html
oletools/doc/oleid.html
oletools/doc/olemap.html
oletools/doc/olemeta.html
oletools/doc/oleobj.html
oletools/doc/oletimes.html
oletools/doc/olevba.html
oletools/doc/pyxswf.html
oletools/doc/rtfobj.html
oletools/olevba.py
setup.py

By replacing the escape character with \e, user defined escape sequences wont be rendered in the output. This prevents malicious actors from performing anti-analysis.
**Before**
**After**

Prevent parsing of escape characters

---

oletools/crypto.py
oletools/msodde.py
oletools/olevba.py

- added support to password discovery during decryption
- added support to decrypted filepath dstfile

password discovery and decrypted filepath dstfile
